Organizations:
  - &RegulatoryDepartmentOrderer
    Name: RegulatoryDepartmentOrderer
    ID: RegulatoryDepartmentOrdererMSP
    MSPDir: ../organizations/ordererOrganizations/ptracing.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentOrdererMSP.admin')"
    OrdererEndpoints:
      - regulatoryDepartmentOrderer.ptracing.com:7050

  - &regulatoryDepartment
    Name: regulatoryDepartmentMSP
    ID: regulatoryDepartmentMSP
    MSPDir: ../organizations/peerOrganizations/regulatoryDepartment.ptracing.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('regulatoryDepartmentMSP.admin', 'regulatoryDepartmentMSP.peer', 'regulatoryDepartmentMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('regulatoryDepartmentMSP.admin', 'regulatoryDepartmentMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('regulatoryDepartmentMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('regulatoryDepartmentMSP.peer')"

  - &farm
    Name: farmMSP
    ID: farmMSP
    MSPDir: ../organizations/peerOrganizations/farm.ptracing.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('farmMSP.admin', 'farmMSP.peer', 'farmMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('farmMSP.admin', 'farmMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('farmMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('farmMSP.peer')"

  - &processor
    Name: processorMSP
    ID: processorMSP
    MSPDir: ../organizations/peerOrganizations/processor.ptracing.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('processorMSP.admin', 'processorMSP.peer', 'processorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('processorMSP.admin', 'processorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('processorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('processorMSP.peer')"

  - &retailer
    Name: retailerMSP
    ID: retailerMSP
    MSPDir: ../organizations/peerOrganizations/retailer.ptracing.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('retailerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('retailerMSP.peer')"

  - &distributor
    Name: distributorMSP
    ID: distributorMSP
    MSPDir: ../organizations/peerOrganizations/distributor.ptracing.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.peer', 'distributorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('distributorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('distributorMSP.peer')"


Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true
    
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - regulatoryDepartmentOrderer.ptracing.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: regulatoryDepartmentOrderer.ptracing.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/ptracing.com/orderers/regulatoryDepartmentOrderer.ptracing.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/ptracing.com/orderers/regulatoryDepartmentOrderer.ptracing.com/tls/server.crt
      Organizations:
        - *RegulatoryDepartmentOrderer
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *regulatoryDepartment
        - *processor
        - *farm
        - *distributor
        - *retailer
      Capabilities: *ApplicationCapabilities