---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &FarmOrdererOrg
    Name: FarmOrdererOrg
    ID: FarmOrdererMSP
    MSPDir: ../organizations/ordererOrganizations/farm.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FarmOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('FarmOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('FarmOrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.farm.com:7050
      
  - &ProcessorOrdererOrg
    Name: ProcessorOrdererOrg
    ID: ProcessorOrdererMSP
    MSPDir: ../organizations/ordererOrganizations/processor.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ProcessorOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ProcessorOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ProcessorOrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.processor.com:7050
      
  - &RegulatoryDepartmentOrdererOrg
    Name: RegulatoryDepartmentOrdererOrg
    ID: RegulatoryDepartmentOrdererMSP
    MSPDir: ../organizations/ordererOrganizations/regulatoryDepartment.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentOrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.regulatoryDepartment.com:7050

  - &RegulatoryDepartment
    Name: RegulatoryDepartmentMSP
    ID: RegulatoryDepartmentMSP
    MSPDir: ../organizations/peerOrganizations/regulatoryDepartment.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentMSP.admin', 'RegulatoryDepartmentMSP.peer', 'RegulatoryDepartmentMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentMSP.admin', 'RegulatoryDepartmentMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegulatoryDepartmentMSP.peer')"
    AnchorPeers:
      - Host: peer0.regulatoryDepartment.com
        Port: 7051

  - &Farm
    Name: FarmMSP
    ID: FarmMSP
    MSPDir: ../organizations/peerOrganizations/farm.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FarmMSP.admin', 'FarmMSP.peer', 'FarmMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('FarmMSP.admin', 'FarmMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('FarmMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('FarmMSP.peer')"
    AnchorPeers:
      - Host: peer0.farm.com
        Port: 8051

  - &Processor
    Name: ProcessorMSP
    ID: ProcessorMSP
    MSPDir: ../organizations/peerOrganizations/processor.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ProcessorMSP.admin', 'ProcessorMSP.peer', 'ProcessorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ProcessorMSP.admin', 'ProcessorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ProcessorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ProcessorMSP.peer')"
    AnchorPeers:
      - Host: peer0.processor.com
        Port: 9051

  - &Distributor
    Name: DistributorMSP
    ID: DistributorMSP
    MSPDir: ../organizations/peerOrganizations/distributor.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DistributorMSP.admin', 'DistributorMSP.peer', 'DistributorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DistributorMSP.admin', 'DistributorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DistributorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DistributorMSP.peer')"
    AnchorPeers:
      - Host: peer0.distributor.com
        Port: 10051

  - &Retailer
    Name: RetailerMSP
    ID: RetailerMSP
    MSPDir: ../organizations/peerOrganizations/retailer.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RetailerMSP.admin', 'RetailerMSP.peer', 'RetailerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RetailerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RetailerMSP.peer')"
    AnchorPeers:
      - Host: peer0.retailer.com
        Port: 11051

################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer.farm.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/farm.com/orderers/orderer.farm.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/farm.com/orderers/orderer.farm.com/tls/server.crt
      - Host: orderer.processor.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/processor.com/orderers/orderer.processor.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/processor.com/orderers/orderer.processor.com/tls/tls/server.crt
      - Host: orderer.regulatoryDepartment.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/regulatoryDepartment.com/orderers/orderer.regulatoryDepartment.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/regulatoryDepartment.com/orderers/orderer.regulatoryDepartment.com/tls/server.crt
    Options:
      TickInterval: 2500ms
      ElectionTick: 5
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: 16 MB
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
  RaftTraceabilityApplicationGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      Organizations:
        - *RegulatoryDepartmentOrdererOrg
        - *FarmOrdererOrg
        - *ProcessorOrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      TraceabilityConsortium:
        Organizations:
          - *RegulatoryDepartment
          - *Farm
          - *Processor
          - *Distributor
          - *Retailer

  TraceabilityChannel:
    Consortium: TraceabilityConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *RegulatoryDepartment
        - *Farm
        - *Processor
        - *Distributor
        - *Retailer
      Capabilities:
        <<: *ApplicationCapabilities